HangManGame/Models/Game.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.EntityFrameworkCore.Internal;
 
namespace HangManGame.Models

{
    public class Game
    {
        public string Word { get; set; }
        public string Answer;
        public List<string> LettersAvailable = new List<string>(new string[] { "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z" });
        public List<string> CorrectlyGuessed { get; set; }
        public List<string> IncorrectlyGuessed { get; set; }
        public int NumberOfGuesses = 10;
        public string Guess { get; set; }
        public bool Win;
        public bool Lose;
        public int MatchingIndex;
        public int Index;
        public string FullWord;

        public Game()
        {
            CorrectlyGuessed = new List<string>();
            IncorrectlyGuessed = new List<string>();
        }
 
        public void GetWord()
        //Gets word that player will be guessing
        {
            Word = wordGenerator.TextFileWordGetter();
            FullWord = Word;
        }

        public void SetDifficulty(string difficulty)
        {
            if (difficulty == "hard")
            {
                NumberOfGuesses = 5;
            }
            else if (difficulty == "medium")
            {
                NumberOfGuesses = 10;
            }
            else if (difficulty == "easy")
            {
                NumberOfGuesses = 15;
            }
        }

        public void GetGuess(string guess)
        //Gets letter that player is guessing is in the word

        {
            Guess = guess;
        }

        public string Temp()
        {
            return Word;
        }
 
        public void GenerateAnswer()
        //Creates string of dashes the same length as the word
        {
            StringBuilder answerBuilder = new StringBuilder();
            for (int i = 0; i < Word.Length; i++)
            {
                answerBuilder.Append("_");
            }
            Answer = answerBuilder.ToString();
            Win = false;
            Lose = false;
            CorrectlyGuessed = new List<string> { };
            IncorrectlyGuessed = new List<string> { };
            NumberOfGuesses = 10;
            Guess = "";
    }
 
        public void UpdateAnswer()
        //Updates answer after a correct guess
        {
           
            int i = Word.IndexOf(Guess);
            StringBuilder answerUpdater = new StringBuilder(Answer);
            while (i != -1)
            {
                answerUpdater[i] = Guess[0];
                Answer = answerUpdater.ToString();
                i = Word.IndexOf(Guess, i + 1);
            }
        }
 
        public void CheckGuess()
        //Checks players guess has not already been guessed, and if it is correct or not
        {
            if (!string.IsNullOrWhiteSpace(Guess))
            //Throws error if no letter entered to guess
            {
                if (!CorrectlyGuessed.Contains(Guess))
                //Checks letter guess is not already in the correctly guessed list
                {
                    if (!IncorrectlyGuessed.Contains(Guess))
                    //Checks letter guess is not already in the incorrectly guessed list
                    {
                        if (Word.Contains(Guess))
                        //Adds letter to the correctly or incorrectly guessed list as needed
                        {
                            CorrectlyGuessed.Add(Guess);
                        }
                        else
                        {
                            ReduceNumberOfGuesses();
                            IncorrectlyGuessed.Add(Guess);
                        }
                    }
                    else
                    {
                       // throw new ArgumentException("That letter has already been guessed!");
                    }
                }
                else
                {
                   // throw new ArgumentException("That letter has already been guessed!");
                }
            }
            else
            {
              //  throw new ArgumentException("Please enter a letter to guess!");
            }
        }
 
        public void CheckIfWon()
        {
            if(Word == Answer)
            {
                Win = true;
            }
        }

        public void ReduceNumberOfGuesses()
        {
            NumberOfGuesses -= 1;
        }

        public void GameOver()
        {
            if (Word != Answer) {
                if (NumberOfGuesses == 0)
                {
                    Lose = true;
                } 
            }
        }
    }
}

HangManGame/Controllers/GameController.cs
using System.Diagnostics;
using System.Web;
using Microsoft.AspNetCore.Mvc;
using HangManGame.Models;
using Microsoft.AspNetCore.Http;
using Newtonsoft.Json;
using System;

namespace HangManGame.Controllers
{
    public class GameController : Controller
    {
        //Create instance of the game
        private static Game game = new Game();
  
        public IActionResult Index()
        {

            //Initialise the game
            game.GetWord();
            game.GenerateAnswer();

            return View("Index", game);
        }

        public IActionResult InPlay()
        {
            game.UpdateAnswer();
            //Display the current state of the game
            return View("Index", game);
        }

        public IActionResult Privacy()
        {
            return View();
        }
        public IActionResult gamePlay()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        [HttpPost]
        public IActionResult SubmitGuess([FromForm] string guess)
        {

            
            //Update the game based on the guess
            game.GetGuess(guess);
            game.CheckGuess();
            game.UpdateAnswer();
            game.CheckIfWon();
            game.GameOver(); 
            return RedirectToAction("InPlay", game);  /// was redirect to action 
           
        }

    }
}
/*
Guesses Ramaining
Correctly Guessed Letters _ _ _ _
Letters Available
Incorrect Guesses
Win or Loose messege
whats being set/ read out 
*/ 

HangManGame/Views/Game/Game.cshtml
@using Microsoft.AspNetCore.Http; 
@using  HangManGame.Models;
@model HangManGame.Models.Game;

    @{
        ViewData["Title"] = "Hang Man Game";
        string guess = Context.Session.GetString("Guess");
        string username = Context.Session.GetString("User");

        Player player = Player.Register(username);
     Game game = new Game();
       game.GetGuess(guess);
     // Game game = Game.Testing(guess);
    }



<div class="page-header">
    <h3> Welcome @player.UserName  </h3>
</div>

<div class="container">
    <p>Please enter your guess</p>
    <form asp-action="localhost:44326/Game" asp-controller="/" method="post">
        <label asp-for="Guess"></label>
        <input asp-for="Guess" placeholder="Your guess goes here"/>
        <button type="submit" class="btn btn-primary">Submit</button>
        @game.Guess
    </form>
</div>

HangManGame/Views/Game/Index.cshtml
@using Microsoft.AspNetCore.Http;
@using HangManGame.Models;
@model HangManGame.Models.Game;

@{
    ViewData["Title"] = "Hang Man Game";
    string guess = Context.Session.GetString("Guess");
    string username = Context.Session.GetString("User");
    string CorrectlyGuessedLetters = Context.Session.GetString("CorrectlyGuessedLetters");


    Player player = Player.Register(username);
    Game game = @Model != null ? @Model : new Game() { CorrectlyGuessed = new List<string>() };
}


@{  

    if (game.Win == true)
    {
        <div class="container-fluid mid-aligned win-lose-card win-lose-delay">
        <p class="space-top"> You Win! :)</p>
        <p class="space-top"> The word was @{@game.FullWord}</p>
        <p class="space-top space-bot"> @Html.ActionLink("New Game", "Index", "Game")</p>
        <img class="space-bot" src="https://media.giphy.com/media/a0h7sAqON67nO/giphy.gif" />
        </div>
    }

    else if (game.Lose == true)
    {
        <div class="container-fluid mid-aligned win-lose-card win-lose-delay">
        <p class="space-top"> You Lose :(</p>
        <p class="space-top"> The word was @{@game.FullWord}</p>
        <p class="space-top space-bot"> @Html.ActionLink("New Game", "Index", "Game")</p>
        <img class="space-bot" src="https://media.giphy.com/media/HvRZOW92Jg2aY/giphy.gif" />
        </div>
    }

    else
    {
        <div class="page-header mid-aligned">
            <h2> Welcome to Hangman, @player.UserName</h2>
        </div>

        <div class="container-fluid body-card">
            <div class="container-fluid playing-card mid-aligned game-text-size">
                <form action="/game/submitguess" method="POST">
                    <span class="left-aligned gameplay-text">Lives remaining: @{@game.NumberOfGuesses}</span>

                    <span class="right-aligned gameplay-text">Your previous guess was: @{@game.Guess}</span>

                    <br />

                    @{
                        if (@game.NumberOfGuesses == 10)
                        {
                            <img class="mid-aligned" src="~/images/10lives.jpg" BackColor="Transparent">
                        }
                        else if (@game.NumberOfGuesses == 9)
                        {
                            <img class="mid-aligned " src="~/images/9lives.jpg">
                        }
                        else if (@game.NumberOfGuesses == 8)
                        {
                            <img class="mid-aligned " src="~/images/8lives.jpg">
                        }
                        else if (@game.NumberOfGuesses == 7)
                        {
                            <img class="mid-aligned " src="~/images/7lives.jpg">
                        }
                        else if (@game.NumberOfGuesses == 6)
                        {
                            <img class="mid-aligned " src="~/images/6lives.jpg">
                        }
                        else if (@game.NumberOfGuesses == 5)
                        {
                            <img class="mid-aligned " src="~/images/5lives.jpg">
                        }
                        else if (@game.NumberOfGuesses == 4)
                        {
                            <img class="mid-aligned " src="~/images/4lives.jpg">
                        }
                        else if (@game.NumberOfGuesses == 3)
                        {
                            <img class="mid-aligned " src="~/images/3lives.jpg">
                        }
                        else if (@game.NumberOfGuesses == 2)
                        {
                            <img class="mid-aligned " src="~/images/2lives.jpg">
                        }
                        else if (@game.NumberOfGuesses == 1)
                        {
                            <img class="mid-aligned " src="~/images/1lives.jpg">
                        }
                        else if (@game.NumberOfGuesses == 0)
                        {
                            <img class="mid-aligned " src="~/images/0lives.jpg">
                        }
                    }

                    <p class="word-text">
                        @foreach (var letter in @game.Answer)
                        {
                            <span class="mid-aligned">@{@letter} </span>
                        }
                    </p>

                    <br />
                    <br />

                    <span class="gameplay-text">Please enter your guess: </span>
                    <input type="text" name="guess" required="" maxlength="1" autofocus />
                    @Html.ValidationMessageFor(m => m.Guess)

                    <button type="submit" class="btn btn-primary">Submit</button>

                    <br />

                    <div class="row">
                        <div class="column">
                            <p class="mid-aligned gameplay-text">Letters correctly guessed: </p>
                            <ul>
                                @foreach (var correctGuess in game.CorrectlyGuessed)
                                {
                                    <span class="mid-aligned gameplay-text"> @correctGuess </span>
                                }
                            </ul>
                        </div>

                        <div class="column">
                            <p class="mid-aligned gameplay-text">Letters incorrectly guessed: </p>
                            <ul>
                                @foreach (var incorrectGuess in game.IncorrectlyGuessed)
                                {
                                    <span class="mid-aligned gameplay-text"> @incorrectGuess </span>
                                }
                            </ul>
                        </div>
                    </div>
                </form>
            </div>
        </div>




    }
}
 
    











